/**
 * Ultracite rules we are not ready to enforce yet.
 *
 * `oxlint.config.mts` extends ultracite/oxlint/{core,react,vitest} then
 * overlays this map so the first slice only rewires the config. Delete a
 * group and fix the hits to turn that slice on. Do not add new offs here
 * unless a later Ultracite release introduces a rule we still cannot take.
 *
 * Vitest extras live in an Ultracite override, so they are also applied
 * from a later override in `oxlint.config.mts` (`deferredVitestUltraciteRules`).
 */
export const deferredUltraciteRules = {
  // --- slice 2 — hooks + type-aware exhaustiveness ---
  // Enable first. rust-native, high signal, no format churn.
  "react/rules-of-hooks": "off",
  "typescript/switch-exhaustiveness-check": "off",
  "typescript/no-deprecated": "off",
  "typescript/only-throw-error": "off",
  "typescript/no-confusing-void-expression": "off",

  // --- slice 3 — waterfalls / barrels / derived effects ---
  "oxc/no-barrel-file": "off",
  "no-await-in-loop": "off",
  "react/no-deriving-state-in-effects": "off",

  // --- slice 4 — any / non-null / unsafe / strict boolean ---
  // Will be noisy. Enable one package at a time if needed.
  "typescript/no-explicit-any": "off",
  "typescript/no-non-null-assertion": "off",
  "typescript/no-unsafe-argument": "off",
  "typescript/no-unsafe-assignment": "off",
  "typescript/no-unsafe-call": "off",
  "typescript/no-unsafe-member-access": "off",
  "typescript/no-unsafe-return": "off",
  "typescript/strict-boolean-expressions": "off",
  "typescript/strict-void-return": "off",
  "typescript/prefer-nullish-coalescing": "off",

  // --- later — perf ---
  "no-useless-call": "off",

  // --- later — pedantic ---
  "accessor-pairs": "off",
  "array-callback-return": "off",
  "jsdoc/require-param-description": "off",
  "jsdoc/require-param-name": "off",
  "jsdoc/require-returns-description": "off",
  "jsdoc/require-throws-type": "off",
  "jsdoc/require-yields-type": "off",
  "max-classes-per-file": "off",
  "max-nested-callbacks": "off",
  "no-case-declarations": "off",
  "no-else-return": "off",
  "no-fallthrough": "off",
  "no-inline-comments": "off",
  "no-inner-declarations": "off",
  "no-lonely-if": "off",
  "no-loop-func": "off",
  "no-negated-condition": "off",
  "no-prototype-builtins": "off",
  "no-redeclare": "off",
  "no-warning-comments": "off",
  "oxc/branches-sharing-code": "off",
  "prefer-promise-reject-errors": "off",
  "react/display-name": "off",
  "react/no-unescaped-entities": "off",
  "require-await": "off",
  "require-unicode-regexp": "off",
  "sort-vars": "off",
  "symbol-description": "off",
  "typescript/ban-ts-comment": "off",
  "typescript/ban-types": "off",
  "typescript/prefer-enum-initializers": "off",
  "typescript/prefer-includes": "off",
  "typescript/prefer-ts-expect-error": "off",
  "unicorn/escape-case": "off",
  "unicorn/no-negated-condition": "off",
  "unicorn/no-useless-undefined": "off",
  "unicorn/prefer-code-point": "off",
  "unicorn/prefer-number-coercion": "off",
  "unicorn/prefer-query-selector": "off",

  // --- later — restriction ---
  "class-methods-use-this": "off",
  complexity: "off",
  "default-case": "off",
  "jsdoc/check-access": "off",
  "jsdoc/empty-tags": "off",
  "jsx-a11y/anchor-ambiguous-text": "off",
  "no-bitwise": "off",
  "no-div-regex": "off",
  "no-empty": "off",
  "no-empty-function": "off",
  "no-eq-null": "off",
  "no-implicit-globals": "off",
  "no-param-reassign": "off",
  "no-plusplus": "off",
  "no-regex-spaces": "off",
  "no-restricted-globals": "off",
  "no-restricted-imports": "off",
  "no-use-before-define": "off",
  "no-void": "off",
  "node/handle-callback-err": "off",
  "node/no-new-require": "off",
  "node/no-path-concat": "off",
  "react/forbid-dom-props": "off",
  "react/forbid-elements": "off",
  "react/invariant": "off",
  "react/no-clone-element": "off",
  "react/no-react-children": "off",
  "react/prefer-function-component": "off",
  "react/rule-suppression": "off",
  "react/syntax": "off",
  "react/todo": "off",
  "react/unsupported-syntax": "off",
  "typescript/no-dynamic-delete": "off",
  "typescript/no-invalid-void-type": "off",
  "typescript/no-restricted-types": "off",
  "typescript/non-nullable-type-assertion-style": "off",
  "typescript/promise-function-async": "off",
  "unicode-bom": "off",
  "unicorn/import-style": "off",
  "unicorn/no-array-reduce": "off",
  "unicorn/prefer-module": "off",
  "unicorn/prefer-number-properties": "off",

  // --- later — correctness ---
  "jsdoc/check-property-names": "off",
  "jsdoc/check-tag-names": "off",
  "jsdoc/implements-on-classes": "off",
  "jsdoc/no-defaults": "off",
  "jsdoc/require-property": "off",
  "jsdoc/require-property-description": "off",
  "jsdoc/require-property-name": "off",
  "jsdoc/require-property-type": "off",
  "jsdoc/require-yields": "off",

  // --- later — style ---
  "arrow-body-style": "off",
  curly: "off",
  "func-name-matching": "off",
  "func-names": "off",
  "func-style": "off",
  "guard-for-in": "off",
  "id-denylist": "off",
  "id-match": "off",
  "import/consistent-type-specifier-style": "off",
  "import/first": "off",
  "import/newline-after-import": "off",
  "jsdoc/no-blank-blocks": "off",
  "jsdoc/require-throws-description": "off",
  "jsdoc/require-yields-description": "off",
  "logical-assignment-operators": "off",
  "no-duplicate-imports": "off",
  "no-extra-label": "off",
  "no-label-var": "off",
  "no-labels": "off",
  "no-lone-blocks": "off",
  "no-multi-str": "off",
  "no-nested-ternary": "off",
  "node/callback-return": "off",
  "node/exports-style": "off",
  "node/global-require": "off",
  "node/no-exports-assign": "off",
  "node/no-mixed-requires": "off",
  "object-shorthand": "off",
  "one-var": "off",
  "operator-assignment": "off",
  "prefer-arrow-callback": "off",
  "prefer-const": "off",
  "prefer-destructuring": "off",
  "prefer-named-capture-group": "off",
  "prefer-numeric-literals": "off",
  "prefer-object-spread": "off",
  "prefer-spread": "off",
  "promise/avoid-new": "off",
  "promise/prefer-await-to-callbacks": "off",
  "promise/prefer-await-to-then": "off",
  "react/function-component-definition": "off",
  "react/hook-use-state": "off",
  "react/jsx-curly-brace-presence": "off",
  "react/jsx-fragments": "off",
  "react/jsx-handler-names": "off",
  "react/jsx-pascal-case": "off",
  "react/no-redundant-should-component-update": "off",
  "react/no-set-state": "off",
  "react/prefer-es6-class": "off",
  "react/state-in-constructor": "off",
  "sort-keys": "off",
  "typescript/array-type": "off",
  "typescript/ban-tslint-comment": "off",
  "typescript/class-literal-property-style": "off",
  "typescript/consistent-generic-constructors": "off",
  "typescript/consistent-indexed-object-style": "off",
  "typescript/consistent-type-assertions": "off",
  "typescript/consistent-type-definitions": "off",
  "typescript/consistent-type-exports": "off",
  "typescript/consistent-type-imports": "off",
  "typescript/dot-notation": "off",
  "typescript/method-signature-style": "off",
  "typescript/no-inferrable-types": "off",
  "typescript/parameter-properties": "off",
  "typescript/prefer-find": "off",
  "typescript/prefer-for-of": "off",
  "typescript/prefer-readonly": "off",
  "typescript/prefer-regexp-exec": "off",
  "typescript/prefer-string-starts-ends-with": "off",
  "typescript/unified-signatures": "off",
  "unicorn/catch-error-name": "off",
  "unicorn/empty-brace-spaces": "off",
  "unicorn/filename-case": "off",
  "unicorn/no-array-method-this-argument": "off",
  "unicorn/no-nested-ternary": "off",
  "unicorn/numeric-separators-style": "off",
  "unicorn/prefer-export-from": "off",
  "unicorn/prefer-logical-operator-over-ternary": "off",
  "unicorn/prefer-reflect-apply": "off",
  "unicorn/prefer-spread": "off",
  "unicorn/prefer-ternary": "off",
  "unicorn/relative-url-style": "off",
  "unicorn/switch-case-braces": "off",
  "unicorn/throw-new-error": "off",
  "vars-on-top": "off",
  "vitest/consistent-test-filename": "off",
  "vitest/max-expects": "off",
  "vitest/max-nested-describe": "off",
  "vitest/no-large-snapshots": "off",
  "vitest/no-restricted-matchers": "off",
  "vitest/no-restricted-vi-methods": "off",
  "vitest/padding-around-after-all-blocks": "off",
  "vitest/padding-around-test-blocks": "off",
  "vitest/prefer-called-exactly-once-with": "off",
  "vitest/prefer-called-once": "off",
  "vitest/prefer-called-with": "off",
  "vitest/prefer-describe-function-title": "off",
  "vitest/prefer-import-in-mock": "off",
  "vitest/prefer-importing-vitest-globals": "off",
  "vitest/prefer-strict-equal": "off",
  "vitest/prefer-to-be-falsy": "off",
  "vitest/prefer-to-be-truthy": "off",
  "vitest/require-top-level-describe": "off",
  yoda: "off",
} as const;

export const deferredVitestUltraciteRules = {
  "vitest/consistent-test-filename": "off",
  "vitest/max-expects": "off",
  "vitest/max-nested-describe": "off",
  "vitest/no-large-snapshots": "off",
  "vitest/no-restricted-matchers": "off",
  "vitest/no-restricted-vi-methods": "off",
  "vitest/padding-around-after-all-blocks": "off",
  "vitest/padding-around-test-blocks": "off",
  "vitest/prefer-called-exactly-once-with": "off",
  "vitest/prefer-called-once": "off",
  "vitest/prefer-called-with": "off",
  "vitest/prefer-describe-function-title": "off",
  "vitest/prefer-import-in-mock": "off",
  "vitest/prefer-importing-vitest-globals": "off",
  "vitest/prefer-strict-equal": "off",
  "vitest/prefer-to-be-falsy": "off",
  "vitest/prefer-to-be-truthy": "off",
  "vitest/require-top-level-describe": "off",
} as const;
