/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DraftRouteImport } from './routes/draft'
import { Route as PullRequestsRouteImport } from './routes/pull-requests'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as SessionSessionIdRouteImport } from './routes/session/$sessionId'
import { Route as SessionFallbackRouteImport } from './routes/session/fallback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoute = DraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const PullRequestsRoute = PullRequestsRouteImport.update({
  id: '/pull-requests',
  path: '/pull-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionFallbackRoute = SessionFallbackRouteImport.update({
  id: '/session/fallback',
  path: '/session/fallback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/draft': typeof DraftRoute
  '/pull-requests': typeof PullRequestsRoute
  '/schedules': typeof SchedulesRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/session/fallback': typeof SessionFallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/draft': typeof DraftRoute
  '/pull-requests': typeof PullRequestsRoute
  '/schedules': typeof SchedulesRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/session/fallback': typeof SessionFallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/draft': typeof DraftRoute
  '/pull-requests': typeof PullRequestsRoute
  '/schedules': typeof SchedulesRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/session/fallback': typeof SessionFallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/draft'
    | '/pull-requests'
    | '/schedules'
    | '/session/$sessionId'
    | '/session/fallback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/draft'
    | '/pull-requests'
    | '/schedules'
    | '/session/$sessionId'
    | '/session/fallback'
  id:
    | '__root__'
    | '/'
    | '/draft'
    | '/pull-requests'
    | '/schedules'
    | '/session/$sessionId'
    | '/session/fallback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DraftRoute: typeof DraftRoute
  PullRequestsRoute: typeof PullRequestsRoute
  SchedulesRoute: typeof SchedulesRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
  SessionFallbackRoute: typeof SessionFallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft': {
      id: '/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof DraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pull-requests': {
      id: '/pull-requests'
      path: '/pull-requests'
      fullPath: '/pull-requests'
      preLoaderRoute: typeof PullRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/fallback': {
      id: '/session/fallback'
      path: '/session/fallback'
      fullPath: '/session/fallback'
      preLoaderRoute: typeof SessionFallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DraftRoute: DraftRoute,
  PullRequestsRoute: PullRequestsRoute,
  SchedulesRoute: SchedulesRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
  SessionFallbackRoute: SessionFallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
